#!/usr/bin/env python3
"""Aggregate conditional Manufacturer beta-VAE FAST-long 3x3 — recovered-035 VAE pool, classifier pool locked.

Read-only aggregator for runs generated by
``run_conditional_beta_vae_manufacturer_fast3x3_mfrrecovered035_clfpoollocked.py``.

Key differences from the cleanmfr aggregator:
  - Candidates were trained on a VAE pool where 035_S_6927 has been restored
    (Manufacturer=SIEMENS patched from direct idaSearch evidence).
  - Only 128_S_2002 is removed per fold (1 subject instead of 2).
  - 035_S_6927 is explicitly excluded from classifier train/dev/test, so the
    supervised AD/CN pool stays locked to cleanmfr/original: n=396, CN=300, AD=96.
  - All comparisons are against the matched clfpoollocked unconditioned baselines.
  - cleanmfr results are cited only as secondary reference context.
"""

from __future__ import annotations

import argparse
import ast
import json
import py_compile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.metrics import balanced_accuracy_score, mean_absolute_error, r2_score, roc_auc_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler


PROJECT_ROOT = Path(__file__).resolve().parents[2]
PREFLIGHT_ROOT = PROJECT_ROOT / "results/revision_bspc_2026/conditional_beta_vae_manufacturer_fast3x3_preflight"
OUTPUT_ROOT = PROJECT_ROOT / "results/revision_bspc_2026/conditional_beta_vae_manufacturer_fastlong_mfrrecovered035_clfpoollocked"
BASE_CLEANMFR_ROOT = PROJECT_ROOT / "results/revision_bspc_2026/conditional_beta_vae_manufacturer_fast3x3_cleanmfr"
PRIMARY_MODEL = "logreg_l2"
PRIMARY_THRESHOLD = "inner_oof_target_sens_ge_0p70_max_spec"
EXPECTED_CANDIDATES = [
    "ch1_0_2_baseline_unconditioned",
    "ch1_0_2_decoder_only_manufacturer",
]
PATCHED_SUBJECT = "035_S_6927"
UNRESOLVED_SUBJECT = "128_S_2002"
EXPECTED_CLASSIFIER_N = 396
EXPECTED_CLASSIFIER_CN = 300
EXPECTED_CLASSIFIER_AD = 96

# Secondary reference from cleanmfr (for context only, not promotion comparison)
CLEANMFR_REFERENCE = {
    "ch1_0_2_baseline_unconditioned": {"auc": np.nan, "pr_auc": np.nan},
    "ch1_0_2_decoder_only_manufacturer": {"auc": np.nan, "pr_auc": np.nan},
}

FASTLONG_TARGET_VALIDATION_ROWS = [
    {
        "selected_target": "[1,0,2]",
        "candidate_id": "ch1_0_2_decoder_only_manufacturer",
        "matched_baseline": "ch1_0_2_baseline_unconditioned",
        "evidence_source": "conditional Manufacturer VAE training-maturity audit",
        "auc_delta_vs_matched_baseline": "positive",
        "pr_auc_delta_vs_matched_baseline": "positive",
        "manufacturer_leakage_reduction": "positive",
        "right_censored_or_near_horizon_folds": "2/3",
        "decision": "selected_for_focused_FAST_long_diagnostic",
    },
    {
        "selected_target": "[1]",
        "candidate_id": "ch1_decoder_only_manufacturer",
        "matched_baseline": "ch1_baseline_unconditioned",
        "evidence_source": "conditional Manufacturer VAE training-maturity audit",
        "auc_delta_vs_matched_baseline": "not_selected",
        "pr_auc_delta_vs_matched_baseline": "not_selected",
        "manufacturer_leakage_reduction": "not_selected",
        "right_censored_or_near_horizon_folds": "not_selected",
        "decision": "not_FAST_long_target",
    },
]


def now_utc() -> str:
    return datetime.now(timezone.utc).isoformat()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("--output-root", type=Path, default=OUTPUT_ROOT)
    parser.add_argument("--preflight-root", type=Path, default=PREFLIGHT_ROOT)
    parser.add_argument("--cleanmfr-root", type=Path, default=BASE_CLEANMFR_ROOT)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--allow-partial", action="store_true")
    return parser.parse_args()


def resolve(path: Path) -> Path:
    return path if path.is_absolute() else PROJECT_ROOT / path


def md_table(df: pd.DataFrame, max_rows: int = 120) -> str:
    if df.empty:
        return "_No rows._\n"
    sub = df.head(max_rows).copy()
    lines = [
        "| " + " | ".join(sub.columns) + " |",
        "| " + " | ".join(["---"] * len(sub.columns)) + " |",
    ]
    for _, row in sub.iterrows():
        vals: List[str] = []
        for col in sub.columns:
            value = row[col]
            if isinstance(value, (float, np.floating)):
                vals.append(f"{value:.6f}" if np.isfinite(value) else "")
            elif pd.isna(value):
                vals.append("")
            else:
                vals.append(str(value).replace("\n", " ").replace("|", "\\|"))
        lines.append("| " + " | ".join(vals) + " |")
    return "\n".join(lines) + "\n"


def write_pair(root: Path, stem: str, df: pd.DataFrame, max_rows: int = 120) -> None:
    df.to_csv(root / f"{stem}.csv", index=False)
    (root / f"{stem}.md").write_text(md_table(df, max_rows=max_rows), encoding="utf-8")


def write_fastlong_target_validation(output_root: Path) -> pd.DataFrame:
    df = pd.DataFrame(FASTLONG_TARGET_VALIDATION_ROWS)
    write_pair(output_root, "fastlong_target_validation", df)
    return df


def read_matrix(preflight_root: Path) -> pd.DataFrame:
    path = preflight_root / "experiment_matrix.csv"
    if not path.exists():
        raise FileNotFoundError(f"Missing preflight matrix: {path}")
    df = pd.read_csv(path)
    missing_candidates = [c for c in EXPECTED_CANDIDATES if c not in set(df["candidate_id"].astype(str))]
    if missing_candidates:
        raise ValueError(f"Preflight matrix missing expected FAST-long candidates: {missing_candidates}")
    df = df[df["candidate_id"].astype(str).isin(EXPECTED_CANDIDATES)].copy()
    order = {candidate_id: idx for idx, candidate_id in enumerate(EXPECTED_CANDIDATES)}
    df["_order"] = df["candidate_id"].map(order)
    df = df.sort_values("_order").drop(columns=["_order"]).reset_index(drop=True)
    if "condition_id" not in df.columns:
        df["condition_id"] = df["candidate_id"].astype(str).str.replace("^ch1_0_2_", "", regex=True).str.replace("^ch1_", "", regex=True)
    if "corr_lambda" not in df.columns:
        df["corr_lambda"] = 0.0
    return df


def parse_channels(value: Any) -> List[int]:
    parsed = ast.literal_eval(str(value))
    if not isinstance(parsed, list):
        raise ValueError(f"Invalid channels field: {value!r}")
    return [int(x) for x in parsed]


def load_run_manifest(output_root: Path, preflight_root: Path) -> pd.DataFrame:
    manifest_path = output_root / "run_manifest.csv"
    matrix = read_matrix(preflight_root)
    rows = []
    for _, row in matrix.iterrows():
        run_dir = output_root / "runs" / str(row["candidate_id"])
        rows.append({
            **row.to_dict(),
            "run_dir": str(run_dir),
            "readout_dir": str(run_dir / f"classifier_only_readout_{row['readout_feature_set']}"),
        })
    canonical = pd.DataFrame(rows)
    if not manifest_path.exists():
        return canonical
    manifest = pd.read_csv(manifest_path)
    if manifest.get("candidate_id", pd.Series(dtype=str)).tolist() == EXPECTED_CANDIDATES:
        return manifest
    if "candidate_id" in manifest.columns:
        manifest_by_id = manifest.set_index("candidate_id", drop=False)
        for idx, row in canonical.iterrows():
            candidate = row["candidate_id"]
            if candidate in manifest_by_id.index:
                for col in ["run_dir", "readout_dir", "big_run_dir"]:
                    if col in manifest_by_id.columns and pd.notna(manifest_by_id.loc[candidate, col]):
                        canonical.at[idx, col] = manifest_by_id.loc[candidate, col]
    return canonical


def add_candidate_metadata(df: pd.DataFrame, row: pd.Series) -> pd.DataFrame:
    out = df.copy()
    for key in ["candidate_id", "condition_id", "channels", "channel_names", "vae_conditioning_mode", "vae_conditioning_vars", "corr_lambda", "readout_feature_set"]:
        if key in row:
            out[key] = row[key]
    return out


def completion_status(row: pd.Series) -> Dict[str, Any]:
    run_dir = Path(str(row["run_dir"]))
    readout_dir = Path(str(row["readout_dir"]))
    fold_ckpts = [(run_dir / f"fold_{fold}" / f"vae_model_fold_{fold}.pt").exists() for fold in range(1, 4)]
    readout_required = [
        readout_dir / "classifier_sweep_pooled_metrics.csv",
        readout_dir / "classifier_sweep_foldwise_metrics.csv",
        readout_dir / "classifier_sweep_predictions.csv",
        readout_dir / "classifier_sweep_thresholds_by_fold.csv",
    ]
    return {
        "candidate_id": row["candidate_id"],
        "run_dir": str(run_dir),
        "readout_dir": str(readout_dir),
        "stage_a_run_config_exists": bool((run_dir / "run_config.json").exists()),
        "stage_a_fold_checkpoints": int(sum(fold_ckpts)),
        "stage_a_complete": bool(all(fold_ckpts) and (run_dir / "run_config.json").exists()),
        "stage_b_required_files": int(sum(p.exists() for p in readout_required)),
        "stage_b_complete": bool(all(p.exists() for p in readout_required)),
    }


def filter_primary_metrics(df: pd.DataFrame, readout_feature_set: str) -> pd.DataFrame:
    out = df.copy()
    if "readout_feature_set" not in out.columns:
        out["readout_feature_set"] = "z_plus_age_sex"
    mask = (
        out["model_name"].astype(str).eq(PRIMARY_MODEL)
        & out["threshold_strategy"].astype(str).eq(PRIMARY_THRESHOLD)
        & out["readout_feature_set"].astype(str).eq(str(readout_feature_set))
    )
    return out.loc[mask].copy()


def collect_stage_b(row: pd.Series) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    readout_dir = Path(str(row["readout_dir"]))
    pooled_rows: List[pd.DataFrame] = []
    fold_rows: List[pd.DataFrame] = []
    threshold_rows: List[pd.DataFrame] = []
    subgroup_rows: List[pd.DataFrame] = []
    confusion_rows: List[pd.DataFrame] = []
    if (readout_dir / "classifier_sweep_pooled_metrics.csv").exists():
        pooled = filter_primary_metrics(pd.read_csv(readout_dir / "classifier_sweep_pooled_metrics.csv"), str(row["readout_feature_set"]))
        if not pooled.empty:
            pooled_rows.append(add_candidate_metadata(pooled, row))
    if (readout_dir / "classifier_sweep_foldwise_metrics.csv").exists():
        fold = filter_primary_metrics(pd.read_csv(readout_dir / "classifier_sweep_foldwise_metrics.csv"), str(row["readout_feature_set"]))
        if not fold.empty:
            fold_rows.append(add_candidate_metadata(fold, row))
    if (readout_dir / "classifier_sweep_thresholds_by_fold.csv").exists():
        th = pd.read_csv(readout_dir / "classifier_sweep_thresholds_by_fold.csv")
        if "readout_feature_set" not in th.columns:
            th["readout_feature_set"] = "z_plus_age_sex"
        th = th[
            th["model_name"].astype(str).eq(PRIMARY_MODEL)
            & th["threshold_strategy"].astype(str).eq(PRIMARY_THRESHOLD)
            & th["readout_feature_set"].astype(str).eq(str(row["readout_feature_set"]))
        ].copy()
        if not th.empty:
            threshold_rows.append(add_candidate_metadata(th, row))
    if (readout_dir / "classifier_sweep_subgroup_metrics_by_manufacturer.csv").exists():
        sg = pd.read_csv(readout_dir / "classifier_sweep_subgroup_metrics_by_manufacturer.csv")
        if "readout_feature_set" not in sg.columns:
            sg["readout_feature_set"] = "z_plus_age_sex"
        sg = sg[
            sg["model_name"].astype(str).eq(PRIMARY_MODEL)
            & sg["threshold_strategy"].astype(str).eq(PRIMARY_THRESHOLD)
            & sg["readout_feature_set"].astype(str).eq(str(row["readout_feature_set"]))
        ].copy()
        if not sg.empty:
            subgroup_rows.append(add_candidate_metadata(sg, row))
    if (readout_dir / "classifier_sweep_confusion_by_fold.csv").exists():
        cf = pd.read_csv(readout_dir / "classifier_sweep_confusion_by_fold.csv")
        if "readout_feature_set" not in cf.columns:
            cf["readout_feature_set"] = "z_plus_age_sex"
        cf = cf[
            cf["model_name"].astype(str).eq(PRIMARY_MODEL)
            & cf["threshold_strategy"].astype(str).eq(PRIMARY_THRESHOLD)
            & cf["readout_feature_set"].astype(str).eq(str(row["readout_feature_set"]))
        ].copy()
        if not cf.empty:
            confusion_rows.append(add_candidate_metadata(cf, row))
    empty = pd.DataFrame()
    return (
        pd.concat(pooled_rows, ignore_index=True, sort=False) if pooled_rows else empty,
        pd.concat(fold_rows, ignore_index=True, sort=False) if fold_rows else empty,
        pd.concat(threshold_rows, ignore_index=True, sort=False) if threshold_rows else empty,
        pd.concat(subgroup_rows, ignore_index=True, sort=False) if subgroup_rows else empty,
        pd.concat(confusion_rows, ignore_index=True, sort=False) if confusion_rows else empty,
    )


def collect_stage_a(row: pd.Series) -> pd.DataFrame:
    run_dir = Path(str(row["run_dir"]))
    frames = []
    for path in sorted(run_dir.glob("all_folds_metrics_MULTI*.csv")):
        try:
            df = pd.read_csv(path)
        except Exception:
            continue
        df["stage_a_metrics_file"] = str(path)
        frames.append(add_candidate_metadata(df, row))
    return pd.concat(frames, ignore_index=True, sort=False) if frames else pd.DataFrame()


def collect_rate_distortion(row: pd.Series) -> pd.DataFrame:
    run_dir = Path(str(row["run_dir"]))
    rows: List[Dict[str, Any]] = []
    for fold in range(1, 4):
        path = run_dir / f"fold_{fold}" / f"fold_{fold}_rate_distortion.csv"
        if not path.exists():
            continue
        df = pd.read_csv(path)
        if df.empty or "L_val_betaMax" not in df.columns:
            continue
        idx = df["L_val_betaMax"].astype(float).idxmin()
        rec = df.loc[idx].to_dict()
        d_val = float(rec.get("D_val", np.nan))
        r_val = float(rec.get("R_val_nats", np.nan))
        beta = 2.5
        rec.update({
            "candidate_id": row["candidate_id"],
            "condition_id": row["condition_id"],
            "channels": row["channels"],
            "readout_feature_set": row["readout_feature_set"],
            "fold": fold,
            "best_epoch_by_val_beta_max": int(rec.get("epoch", idx + 1)),
            "val_kld_over_recon": r_val / d_val if np.isfinite(r_val) and np.isfinite(d_val) and d_val else np.nan,
            "val_beta_kld_over_recon": beta * r_val / d_val if np.isfinite(r_val) and np.isfinite(d_val) and d_val else np.nan,
            "final_epoch_in_rd_file": int(df["epoch"].max()) if "epoch" in df.columns else np.nan,
        })
        rows.append(rec)
    return pd.DataFrame(rows)


def collect_latent_information(row: pd.Series) -> pd.DataFrame:
    run_dir = Path(str(row["run_dir"]))
    frames = []
    for fold in range(1, 4):
        for split in ["trainDev", "test"]:
            path = run_dir / f"fold_{fold}" / f"fold_{fold}_{split}_latent_info_summary.csv"
            if not path.exists():
                continue
            df = pd.read_csv(path)
            df["fold"] = fold
            df["latent_split"] = split
            frames.append(add_candidate_metadata(df, row))
    return pd.concat(frames, ignore_index=True, sort=False) if frames else pd.DataFrame()


def collect_scanner_leakage(row: pd.Series) -> pd.DataFrame:
    run_dir = Path(str(row["run_dir"]))
    frames = []
    for fold in range(1, 4):
        for split, name in [("trainDev", f"fold_{fold}_scanner_leakage_summary.csv"), ("test", f"fold_{fold}_test_scanner_leakage_summary.csv")]:
            path = run_dir / f"fold_{fold}" / name
            if not path.exists():
                continue
            df = pd.read_csv(path)
            df["fold"] = fold
            df["leakage_split"] = split
            if {"acc_site_latent", "acc_site_raw"}.issubset(df.columns):
                df["latent_minus_raw"] = df["acc_site_latent"] - df["acc_site_raw"]
            frames.append(add_candidate_metadata(df, row))
    return pd.concat(frames, ignore_index=True, sort=False) if frames else pd.DataFrame()


def collect_vae_pool_filter_qc(row: pd.Series) -> Tuple[pd.DataFrame, pd.DataFrame]:
    run_dir = Path(str(row["run_dir"]))
    removed_frames: List[pd.DataFrame] = []
    summary_rows: List[Dict[str, Any]] = []
    for fold in range(1, 4):
        fold_dir = run_dir / f"fold_{fold}"
        removed_path = fold_dir / f"vae_pool_required_metadata_removed_fold_{fold}.csv"
        summary_path = fold_dir / f"vae_pool_required_metadata_filter_summary_fold_{fold}.json"
        if removed_path.exists():
            try:
                df = pd.read_csv(removed_path)
                df["candidate_id"] = row["candidate_id"]
                df["condition_id"] = row["condition_id"]
                removed_frames.append(df)
            except Exception:
                pass
        if summary_path.exists():
            try:
                with open(summary_path, encoding="utf-8") as f:
                    s = json.load(f)
                summary_rows.append({
                    "candidate_id": row["candidate_id"],
                    "condition_id": row["condition_id"],
                    "fold": s.get("fold", fold),
                    "required_cols": "|".join(s.get("required_cols", [])),
                    "n_vae_pool_before_filter": s.get("n_vae_pool_before_filter", np.nan),
                    "n_removed": s.get("n_removed", np.nan),
                    "n_vae_pool_after_filter": s.get("n_vae_pool_after_filter", np.nan),
                })
            except Exception:
                pass
    return (
        pd.concat(removed_frames, ignore_index=True, sort=False) if removed_frames else pd.DataFrame(),
        pd.DataFrame(summary_rows),
    )


def _split_subjects(path: Path) -> Tuple[set, pd.DataFrame]:
    if not path.exists():
        return set(), pd.DataFrame()
    df = pd.read_csv(path)
    subjects = set(df.get("SubjectID", pd.Series(dtype=str)).astype(str).tolist())
    return subjects, df


def collect_supervised_exclusion_audit(manifest: pd.DataFrame) -> pd.DataFrame:
    rows: List[Dict[str, Any]] = []
    for _, row in manifest.iterrows():
        run_dir = Path(str(row["run_dir"]))
        for fold in range(1, 4):
            for split, filename in [("train_dev", "train_dev_subjects_fold.csv"), ("test", "test_subjects_fold.csv")]:
                path = run_dir / f"fold_{fold}" / filename
                subjects, df = _split_subjects(path)
                counts = df.get("ResearchGroup_Mapped", pd.Series(dtype=str)).astype(str).value_counts().to_dict() if not df.empty else {}
                contains_035 = PATCHED_SUBJECT in subjects
                contains_128 = UNRESOLVED_SUBJECT in subjects
                status = "missing" if df.empty else ("violation" if contains_035 or contains_128 else "ok")
                rows.append({
                    "candidate_id": row["candidate_id"],
                    "fold": fold,
                    "split": split,
                    "path": str(path),
                    "status": status,
                    "n": int(len(df)) if not df.empty else 0,
                    "CN": int(counts.get("CN", 0)),
                    "AD": int(counts.get("AD", 0)),
                    "contains_035_S_6927": bool(contains_035),
                    "contains_128_S_2002": bool(contains_128),
                })
    return pd.DataFrame(rows)


def collect_classifier_pool_identity_vs_cleanmfr(manifest: pd.DataFrame, cleanmfr_root: Path) -> pd.DataFrame:
    rows: List[Dict[str, Any]] = []
    for _, row in manifest.iterrows():
        candidate = str(row["candidate_id"])
        run_dir = Path(str(row["run_dir"]))
        clean_run_dir = cleanmfr_root / "runs" / candidate
        for fold in range(1, 4):
            for split, filename in [("train_dev", "train_dev_subjects_fold.csv"), ("test", "test_subjects_fold.csv")]:
                this_subjects, this_df = _split_subjects(run_dir / f"fold_{fold}" / filename)
                clean_subjects, clean_df = _split_subjects(clean_run_dir / f"fold_{fold}" / filename)
                only_this = sorted(this_subjects - clean_subjects)
                only_clean = sorted(clean_subjects - this_subjects)
                status = "missing" if this_df.empty or clean_df.empty else ("identical" if not only_this and not only_clean else "different")
                rows.append({
                    "candidate_id": candidate,
                    "fold": fold,
                    "split": split,
                    "status": status,
                    "n_this": int(len(this_subjects)),
                    "n_cleanmfr": int(len(clean_subjects)),
                    "symmetric_difference_n": int(len(only_this) + len(only_clean)),
                    "only_this": "|".join(only_this[:20]),
                    "only_cleanmfr": "|".join(only_clean[:20]),
                })
    return pd.DataFrame(rows)


def classifier_pooled_metric_audit(primary: pd.DataFrame) -> pd.DataFrame:
    rows: List[Dict[str, Any]] = []
    for _, row in primary.iterrows():
        n = int(row.get("n", -1)) if pd.notna(row.get("n", np.nan)) else -1
        n_cn = int(row.get("n_cn", -1)) if pd.notna(row.get("n_cn", np.nan)) else -1
        n_ad = int(row.get("n_ad", -1)) if pd.notna(row.get("n_ad", np.nan)) else -1
        rows.append({
            "candidate_id": row.get("candidate_id", ""),
            "n": n,
            "n_cn": n_cn,
            "n_ad": n_ad,
            "expected_n": EXPECTED_CLASSIFIER_N,
            "expected_cn": EXPECTED_CLASSIFIER_CN,
            "expected_ad": EXPECTED_CLASSIFIER_AD,
            "pool_locked_ok": bool(n == EXPECTED_CLASSIFIER_N and n_cn == EXPECTED_CLASSIFIER_CN and n_ad == EXPECTED_CLASSIFIER_AD),
        })
    return pd.DataFrame(rows)


def mu_cols(df: pd.DataFrame) -> List[str]:
    return [c for c in df.columns if c.startswith("mu_")]


def sex_to_binary(values: pd.Series) -> Tuple[np.ndarray, bool]:
    mapped = values.astype(str).str.upper().map({"F": 1, "FEMALE": 1, "M": 0, "MALE": 0})
    ok = not mapped.isna().any() and mapped.nunique(dropna=True) == 2
    return mapped.to_numpy(dtype=float), bool(ok)


def normalize_manufacturer(values: pd.Series) -> pd.Series:
    raw = values.astype(str).str.strip().str.upper()
    return raw.replace({
        "PHILIPS MEDICAL SYSTEMS": "PHILIPS", "PHILIPS": "PHILIPS",
        "SIEMENS": "SIEMENS", "SIEMENS HEALTHCARE": "SIEMENS", "SIEMENS HEALTHINEERS": "SIEMENS",
        "GE": "GE", "GE MEDICAL SYSTEMS": "GE",
    })


def categorical_predictability_rows(*, base: Dict[str, Any], target_name: str, train_values: pd.Series, test_values: pd.Series, x_train: np.ndarray, x_test: np.ndarray) -> List[Dict[str, Any]]:
    if target_name == "Manufacturer":
        y_train_s = normalize_manufacturer(train_values)
        y_test_s = normalize_manufacturer(test_values)
    else:
        y_train_s = train_values.astype(str).str.strip()
        y_test_s = test_values.astype(str).str.strip()
    missing_like = {"", "NAN", "NA", "NONE", "<NA>"}
    y_train_s = y_train_s.where(~y_train_s.astype(str).str.upper().isin(missing_like))
    y_test_s = y_test_s.where(~y_test_s.astype(str).str.upper().isin(missing_like))
    if y_train_s.isna().any() or y_test_s.isna().any():
        return []
    train_classes = sorted(y_train_s.unique().tolist())
    test_classes = sorted(y_test_s.unique().tolist())
    if len(train_classes) < 2 or len(test_classes) < 2 or not set(test_classes).issubset(set(train_classes)):
        return []
    clf = make_pipeline(StandardScaler(), LogisticRegression(C=1.0, class_weight="balanced", max_iter=3000, solver="lbfgs"))
    clf.fit(x_train, y_train_s.to_numpy())
    pred = clf.predict(x_test)
    return [{**base, "target": target_name, "metric_primary": "balanced_accuracy", "r2": np.nan, "mae": np.nan, "balanced_accuracy": float(balanced_accuracy_score(y_test_s.to_numpy(), pred)), "roc_auc": np.nan, "train_classes": "|".join(train_classes), "test_classes": "|".join(test_classes)}]


def collect_covariate_predictability(row: pd.Series) -> pd.DataFrame:
    readout_dir = Path(str(row["readout_dir"]))
    cache = readout_dir / "latent_cache"
    rows: List[Dict[str, Any]] = []
    for fold in range(1, 4):
        train_path = cache / f"fold_{fold}_trainDev_latent_mu.csv"
        test_path = cache / f"fold_{fold}_test_latent_mu.csv"
        if not train_path.exists() or not test_path.exists():
            continue
        train = pd.read_csv(train_path)
        test = pd.read_csv(test_path)
        cols = mu_cols(train)
        if not cols:
            continue
        x_train = train[cols].to_numpy(dtype=float)
        x_test = test[cols].to_numpy(dtype=float)
        base = {"candidate_id": row["candidate_id"], "condition_id": row["condition_id"], "channels": row["channels"], "readout_feature_set": row["readout_feature_set"], "fold": fold, "n_trainDev": int(len(train)), "n_test": int(len(test))}
        if "Age" in train.columns and "Age" in test.columns:
            y_train = pd.to_numeric(train["Age"], errors="coerce")
            y_test = pd.to_numeric(test["Age"], errors="coerce")
            if not y_train.isna().any() and not y_test.isna().any():
                model = make_pipeline(StandardScaler(), Ridge(alpha=1.0))
                model.fit(x_train, y_train.to_numpy(dtype=float))
                pred = model.predict(x_test)
                rows.append({**base, "target": "Age", "metric_primary": "r2", "r2": float(r2_score(y_test, pred)), "mae": float(mean_absolute_error(y_test, pred)), "balanced_accuracy": np.nan, "roc_auc": np.nan})
        if "Sex" in train.columns and "Sex" in test.columns:
            y_train, ok_train = sex_to_binary(train["Sex"])
            y_test, ok_test = sex_to_binary(test["Sex"])
            if ok_train and ok_test:
                clf = make_pipeline(StandardScaler(), LogisticRegression(C=1.0, class_weight="balanced", max_iter=2000, solver="lbfgs"))
                clf.fit(x_train, y_train.astype(int))
                pred = clf.predict(x_test)
                try:
                    score = clf.predict_proba(x_test)[:, 1]
                    auc = roc_auc_score(y_test.astype(int), score)
                except Exception:
                    auc = np.nan
                rows.append({**base, "target": "Sex", "metric_primary": "balanced_accuracy", "r2": np.nan, "mae": np.nan, "balanced_accuracy": float(balanced_accuracy_score(y_test.astype(int), pred)), "roc_auc": float(auc) if np.isfinite(auc) else np.nan})
        for target_name in ["Manufacturer", "SiteCode"]:
            if target_name in train.columns and target_name in test.columns:
                rows.extend(categorical_predictability_rows(base=base, target_name=target_name, train_values=train[target_name], test_values=test[target_name], x_train=x_train, x_test=x_test))
    return pd.DataFrame(rows)


def summarize_by_candidate(df: pd.DataFrame, value_cols: Sequence[str], group_cols: Sequence[str]) -> pd.DataFrame:
    if df.empty:
        return pd.DataFrame()
    cols = [c for c in value_cols if c in df.columns]
    if not cols:
        return pd.DataFrame()
    return df.groupby(list(group_cols), dropna=False)[cols].mean(numeric_only=True).reset_index()


def latent_info_wide(latent_info: pd.DataFrame) -> pd.DataFrame:
    if latent_info.empty:
        return pd.DataFrame()
    sub = latent_info[latent_info["latent_split"].eq("test")].copy()
    cols = [c for c in ["mi_sum_nats", "mi_mean_nats", "n_active", "frac_active", "total_correlation_nats"] if c in sub.columns]
    return sub.groupby(["candidate_id", "condition_id", "channels", "readout_feature_set", "variable"], dropna=False)[cols].mean(numeric_only=True).reset_index()


def leakage_summary(leakage: pd.DataFrame) -> pd.DataFrame:
    if leakage.empty:
        return pd.DataFrame()
    cols = [c for c in ["acc_site_raw", "acc_site_latent", "latent_minus_raw"] if c in leakage.columns]
    return leakage[leakage["leakage_split"].eq("test")].groupby(["candidate_id", "condition_id", "channels", "readout_feature_set"], dropna=False)[cols].mean(numeric_only=True).reset_index()


def covariate_summary(pred: pd.DataFrame) -> pd.DataFrame:
    if pred.empty:
        return pd.DataFrame()
    cols = [c for c in ["r2", "mae", "balanced_accuracy", "roc_auc"] if c in pred.columns]
    return pred.groupby(["candidate_id", "condition_id", "channels", "readout_feature_set", "target"], dropna=False)[cols].mean(numeric_only=True).reset_index()


def get_baseline_row(primary: pd.DataFrame, channels: str, readout: str) -> Optional[pd.Series]:
    baseline_id = f"{'ch1_0_2' if channels == '[1, 0, 2]' else 'ch1'}_baseline_unconditioned"
    rows = primary[primary["candidate_id"].astype(str).eq(baseline_id)]
    if rows.empty:
        return None
    return rows.iloc[0]


def mean_mi_for(latent: pd.DataFrame, candidate_id: str, variable: str) -> float:
    if latent.empty:
        return np.nan
    sub = latent[latent["candidate_id"].astype(str).eq(candidate_id) & latent["latent_split"].astype(str).eq("test") & latent["variable"].astype(str).eq(variable)]
    if sub.empty or "mi_sum_nats" not in sub.columns:
        return np.nan
    return float(pd.to_numeric(sub["mi_sum_nats"], errors="coerce").mean())


def mean_leakage_for(leakage: pd.DataFrame, candidate_id: str) -> float:
    if leakage.empty or "acc_site_latent" not in leakage.columns:
        return np.nan
    sub = leakage[leakage["candidate_id"].astype(str).eq(candidate_id) & leakage["leakage_split"].astype(str).eq("test")]
    if sub.empty:
        return np.nan
    return float(pd.to_numeric(sub["acc_site_latent"], errors="coerce").mean())


def mean_predictability_for(predictability: pd.DataFrame, candidate_id: str, target: str) -> float:
    if predictability.empty or "balanced_accuracy" not in predictability.columns:
        return np.nan
    sub = predictability[predictability["candidate_id"].astype(str).eq(candidate_id) & predictability["target"].astype(str).eq(target)]
    if sub.empty:
        return np.nan
    return float(pd.to_numeric(sub["balanced_accuracy"], errors="coerce").mean())


def worst_manufacturer_metric(subgroups: pd.DataFrame, candidate_id: str, metric: str) -> float:
    if subgroups.empty or metric not in subgroups.columns:
        return np.nan
    sub = subgroups[subgroups["candidate_id"].astype(str).eq(candidate_id)].copy()
    if sub.empty:
        return np.nan
    return float(pd.to_numeric(sub[metric], errors="coerce").min())


def recommendation(
    primary: pd.DataFrame,
    latent: pd.DataFrame,
    leakage: pd.DataFrame,
    predictability: pd.DataFrame,
    subgroups: pd.DataFrame,
    pooled_metric_audit: pd.DataFrame,
) -> str:
    lines = [
        "# Conditional Manufacturer beta-VAE FAST-long 3x3 — recovered-035 VAE pool, classifier pool locked — Recommendation",
        "",
        "## Baseline validity",
        "",
        "Both focused FAST-long candidates in this experiment used `--vae_required_metadata_cols Manufacturer`,",
        "the branch-local patched metadata (035_S_6927 Manufacturer=SIEMENS restored),",
        "and `--classifier_exclude_subject_ids 035_S_6927`.",
        "",
        "**Primary comparators: clfpoollocked matched baselines only.**",
        "  - `ch1_0_2_baseline_unconditioned` → baseline for `ch1_0_2_decoder_only_manufacturer`",
        "",
        "The FAST-long target is `[1,0,2]`, not `[1]`, because the training-maturity audit identified",
        "`ch1_0_2_decoder_only_manufacturer` as the strongest valid diagnostic candidate: positive",
        "AUC and PR-AUC deltas, positive Manufacturer-leakage reduction, and 2/3 right-censored or",
        "near-horizon folds.",
        "",
        "cleanmfr is used only to audit classifier split identity, not as a primary performance comparator.",
        "",
        "## Decision rule",
        "",
        "Recommend FULL 5x5 only if Manufacturer conditioning improves or matches AUC/PR-AUC versus",
        "the matched clfpoollocked unconditioned baseline, has Sens >= 0.70, does not worsen BA/F1,",
        "reduces manufacturer/site leakage or Manufacturer predictability from z.",
        "",
    ]
    if primary.empty:
        lines.append("No completed Stage B primary metrics found. No FULL confirmation justified yet.")
        return "\n".join(lines) + "\n"

    if not pooled_metric_audit.empty and not pooled_metric_audit["pool_locked_ok"].all():
        lines.append("## Classifier Pool Lock Failure")
        lines.append("")
        lines.append("At least one candidate did not preserve n=396, CN=300, AD=96. Treat results as diagnostic only.")
        lines.append("")

    numeric_cols = ["auc", "pr_auc", "balanced_accuracy", "sensitivity", "specificity", "f1"]
    for col in numeric_cols:
        if col in primary.columns:
            primary[col] = pd.to_numeric(primary[col], errors="coerce")

    candidates = primary[primary["vae_conditioning_mode"].astype(str).eq("decoder_only")].copy()
    decisions = []
    for _, cand in candidates.iterrows():
        readout = str(cand["readout_feature_set"])
        baseline = get_baseline_row(primary, str(cand["channels"]), readout)
        if baseline is None:
            decisions.append((cand["candidate_id"], "no_mfrrecovered035_baseline_found", False))
            continue

        mfr_mi = mean_mi_for(latent, str(cand["candidate_id"]), "Manufacturer")
        base_mfr_mi = mean_mi_for(latent, str(baseline["candidate_id"]), "Manufacturer")
        mfr_pred = mean_predictability_for(predictability, str(cand["candidate_id"]), "Manufacturer")
        base_mfr_pred = mean_predictability_for(predictability, str(baseline["candidate_id"]), "Manufacturer")
        leak = mean_leakage_for(leakage, str(cand["candidate_id"]))
        base_leak = mean_leakage_for(leakage, str(baseline["candidate_id"]))
        worst_ba = worst_manufacturer_metric(subgroups, str(cand["candidate_id"]), "balanced_accuracy")
        base_worst_ba = worst_manufacturer_metric(subgroups, str(baseline["candidate_id"]), "balanced_accuracy")

        mi_ok = not (np.isfinite(mfr_mi) and np.isfinite(base_mfr_mi)) or mfr_mi <= base_mfr_mi
        pred_ok = not (np.isfinite(mfr_pred) and np.isfinite(base_mfr_pred)) or mfr_pred <= base_mfr_pred
        leak_ok = not (np.isfinite(leak) and np.isfinite(base_leak)) or leak <= base_leak
        nuisance_ok = mi_ok or pred_ok or leak_ok
        subgroup_ok = not (np.isfinite(worst_ba) and np.isfinite(base_worst_ba)) or worst_ba >= base_worst_ba - 0.005

        ok = (
            float(cand.get("auc", np.nan)) >= float(baseline.get("auc", np.inf))
            and float(cand.get("pr_auc", np.nan)) >= float(baseline.get("pr_auc", np.inf))
            and float(cand.get("sensitivity", np.nan)) >= 0.70
            and float(cand.get("balanced_accuracy", np.nan)) >= float(baseline.get("balanced_accuracy", np.inf))
            and float(cand.get("f1", np.nan)) >= float(baseline.get("f1", np.inf))
            and nuisance_ok
            and subgroup_ok
        )

        # Add cleanmfr reference as secondary context
        cleanmfr_ref = CLEANMFR_REFERENCE.get(str(cand["candidate_id"]), {})
        cleanmfr_base_ref = CLEANMFR_REFERENCE.get(str(baseline["candidate_id"]), {})
        cleanmfr_note = ""
        if cleanmfr_ref and cleanmfr_base_ref:
            cleanmfr_note = (
                f" [cleanmfr secondary ref: cand AUC={cleanmfr_ref.get('auc','?'):.4f}/"
                f"PR-AUC={cleanmfr_ref.get('pr_auc','?'):.4f} vs "
                f"cleanmfr_base AUC={cleanmfr_base_ref.get('auc','?'):.4f}/"
                f"PR-AUC={cleanmfr_base_ref.get('pr_auc','?'):.4f}]"
            )

        reason = (
            f"vs clfpoollocked baseline {baseline['candidate_id']}: "
            f"AUC {cand.get('auc', np.nan):.4f} vs {baseline.get('auc', np.nan):.4f}, "
            f"PR-AUC {cand.get('pr_auc', np.nan):.4f} vs {baseline.get('pr_auc', np.nan):.4f}, "
            f"ManufacturerMI {mfr_mi:.4f} vs {base_mfr_mi:.4f}, "
            f"ManufacturerPredBA {mfr_pred:.4f} vs {base_mfr_pred:.4f}, "
            f"latent leakage {leak:.4f} vs {base_leak:.4f}"
            + cleanmfr_note
        )
        decisions.append((cand["candidate_id"], reason, ok))

    promoted = [d for d in decisions if d[2]]
    if promoted:
        lines.append("Recommended for one controlled FULL 5x5 confirmation:")
        for candidate_id, reason, _ in promoted:
            lines.append(f"- `{candidate_id}`: {reason}")
    else:
        lines.append("No conditional candidate satisfies the full promotion rule based on currently completed outputs.")
    lines.append("")
    lines.append("Candidate checks (vs matched clfpoollocked baselines):")
    for candidate_id, reason, ok in decisions:
        lines.append(f"- `{candidate_id}`: {'PASS' if ok else 'NO_PROMOTE'}; {reason}")
    lines.append("")
    lines.append("## Secondary reference: cleanmfr results")
    lines.append("")
    lines.append("| candidate_id | cleanmfr_auc | cleanmfr_pr_auc |")
    lines.append("| --- | --- | --- |")
    for cid, vals in CLEANMFR_REFERENCE.items():
        lines.append(f"| {cid} | {vals['auc']:.4f} | {vals['pr_auc']:.4f} |")
    lines.append("")
    lines.append("Note: cleanmfr is retained here only as classifier-pool identity reference.")
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    preflight_root = resolve(args.preflight_root)
    output_root = resolve(args.output_root)
    cleanmfr_root = resolve(args.cleanmfr_root)
    output_root.mkdir(parents=True, exist_ok=True)

    try:
        py_compile.compile(str(Path(__file__).resolve()), doraise=True)
        py_compile_status = "ok"
    except Exception as exc:
        py_compile_status = f"failed: {exc}"

    manifest = load_run_manifest(output_root, preflight_root)
    target_validation = write_fastlong_target_validation(output_root)
    manifest_order_ok = manifest["candidate_id"].tolist() == EXPECTED_CANDIDATES
    status = pd.DataFrame([completion_status(row) for _, row in manifest.iterrows()])
    write_pair(output_root, "candidate_completion_status", status)

    command_log = {
        "created_utc": now_utc(),
        "script": str(Path(__file__).resolve().relative_to(PROJECT_ROOT)),
        "output_root": str(output_root),
        "preflight_root": str(preflight_root),
        "cleanmfr_root": str(cleanmfr_root),
        "dry_run": bool(args.dry_run),
        "py_compile": py_compile_status,
        "manifest_order_ok": manifest_order_ok,
        "fastlong_target_validation": target_validation.to_dict(orient="records"),
        "training_launched": False,
        "tensor_modified": False,
        "metadata_datos_modified": False,
        "ledger_modified": False,
        "model_outputs_modified": False,
        "vae_required_metadata_cols": ["Manufacturer"],
        "baseline_note": (
            "Primary comparator is the clfpoollocked ch1_0_2 matched baseline only. "
            "cleanmfr is used only to audit classifier pool identity."
        ),
        "target_note": (
            "FAST-long targets ch1_0_2_decoder_only_manufacturer because the training-maturity audit "
            "found positive AUC/PR-AUC deltas, leakage reduction, and 2/3 right-censored or near-horizon folds."
        ),
        "patch_note": (
            "035_S_6927 restored to VAE pool with Manufacturer=SIEMENS (direct evidence from idaSearch). "
            "035_S_6927 is explicitly excluded from supervised classifier folds. "
            "128_S_2002 remains excluded (unresolvable)."
        ),
    }

    if args.dry_run:
        print(json.dumps(command_log, indent=2))
        print(status.to_string(index=False))
        (output_root / "command_log.json").write_text(json.dumps(command_log, indent=2), encoding="utf-8")
        return 0

    if not args.allow_partial and not status["stage_b_complete"].all():
        incomplete = status.loc[~status["stage_b_complete"], "candidate_id"].tolist()
        raise SystemExit(f"Missing complete Stage B outputs: {incomplete}. Use --allow-partial to aggregate completed candidates only.")

    primary_frames: List[pd.DataFrame] = []
    fold_frames: List[pd.DataFrame] = []
    threshold_frames: List[pd.DataFrame] = []
    subgroup_frames: List[pd.DataFrame] = []
    confusion_frames: List[pd.DataFrame] = []
    stagea_frames: List[pd.DataFrame] = []
    rd_frames: List[pd.DataFrame] = []
    latent_frames: List[pd.DataFrame] = []
    leakage_frames: List[pd.DataFrame] = []
    predict_frames: List[pd.DataFrame] = []
    qc_removed_frames: List[pd.DataFrame] = []
    qc_summary_frames: List[pd.DataFrame] = []

    for _, row in manifest.iterrows():
        if not Path(str(row["readout_dir"])).exists():
            continue
        primary, foldwise, thresholds, subgroups, confusions = collect_stage_b(row)
        for frame, bucket in [(primary, primary_frames), (foldwise, fold_frames), (thresholds, threshold_frames), (subgroups, subgroup_frames), (confusions, confusion_frames)]:
            if not frame.empty:
                bucket.append(frame)
        for frame, bucket in [(collect_stage_a(row), stagea_frames), (collect_rate_distortion(row), rd_frames), (collect_latent_information(row), latent_frames), (collect_scanner_leakage(row), leakage_frames), (collect_covariate_predictability(row), predict_frames)]:
            if not frame.empty:
                bucket.append(frame)
        qc_removed, qc_summary = collect_vae_pool_filter_qc(row)
        if not qc_removed.empty:
            qc_removed_frames.append(qc_removed)
        if not qc_summary.empty:
            qc_summary_frames.append(qc_summary)

    primary = pd.concat(primary_frames, ignore_index=True, sort=False) if primary_frames else pd.DataFrame()
    foldwise = pd.concat(fold_frames, ignore_index=True, sort=False) if fold_frames else pd.DataFrame()
    thresholds = pd.concat(threshold_frames, ignore_index=True, sort=False) if threshold_frames else pd.DataFrame()
    subgroups = pd.concat(subgroup_frames, ignore_index=True, sort=False) if subgroup_frames else pd.DataFrame()
    confusions = pd.concat(confusion_frames, ignore_index=True, sort=False) if confusion_frames else pd.DataFrame()
    stagea = pd.concat(stagea_frames, ignore_index=True, sort=False) if stagea_frames else pd.DataFrame()
    rate_distortion = pd.concat(rd_frames, ignore_index=True, sort=False) if rd_frames else pd.DataFrame()
    latent_info = pd.concat(latent_frames, ignore_index=True, sort=False) if latent_frames else pd.DataFrame()
    leakage = pd.concat(leakage_frames, ignore_index=True, sort=False) if leakage_frames else pd.DataFrame()
    predictability = pd.concat(predict_frames, ignore_index=True, sort=False) if predict_frames else pd.DataFrame()
    qc_removed_all = pd.concat(qc_removed_frames, ignore_index=True, sort=False) if qc_removed_frames else pd.DataFrame()
    qc_summary_all = pd.concat(qc_summary_frames, ignore_index=True, sort=False) if qc_summary_frames else pd.DataFrame()

    if not primary.empty and "auc" in primary.columns:
        primary = primary.sort_values(["channels", "auc", "pr_auc"], ascending=[True, False, False])

    supervised_exclusion = collect_supervised_exclusion_audit(manifest)
    classifier_identity = collect_classifier_pool_identity_vs_cleanmfr(manifest, cleanmfr_root)
    pooled_metric_audit = classifier_pooled_metric_audit(primary)

    write_pair(output_root, "primary_results", primary)
    write_pair(output_root, "foldwise_metrics", foldwise)
    write_pair(output_root, "thresholds_by_fold", thresholds)
    write_pair(output_root, "manufacturer_subgroup_metrics", subgroups)
    write_pair(output_root, "confusion_by_fold", confusions)
    write_pair(output_root, "stagea_logreg_summary", stagea)
    write_pair(output_root, "rate_distortion_by_candidate_fold", rate_distortion)
    write_pair(output_root, "latent_information_summary", latent_info)
    write_pair(output_root, "latent_information_by_candidate_variable", latent_info_wide(latent_info))
    write_pair(output_root, "scanner_manufacturer_leakage", leakage)
    write_pair(output_root, "scanner_manufacturer_leakage_summary", leakage_summary(leakage))
    write_pair(output_root, "latent_covariate_predictability", predictability)
    write_pair(output_root, "latent_covariate_predictability_summary", covariate_summary(predictability))
    if not predictability.empty and "target" in predictability.columns:
        write_pair(output_root, "manufacturer_predictability_from_z", predictability[predictability["target"].astype(str).eq("Manufacturer")].copy())
    else:
        write_pair(output_root, "manufacturer_predictability_from_z", pd.DataFrame())
    write_pair(output_root, "vae_pool_filter_removed_subjects", qc_removed_all)
    write_pair(output_root, "vae_pool_filter_summary_by_candidate_fold", qc_summary_all)
    write_pair(output_root, "supervised_exclusion_audit", supervised_exclusion)
    write_pair(output_root, "classifier_pool_identity_vs_cleanmfr", classifier_identity)
    write_pair(output_root, "classifier_pooled_metric_audit", pooled_metric_audit)
    patch_audit_path = output_root / "patch_audit.csv"
    if patch_audit_path.exists():
        try:
            write_pair(output_root, "patch_audit", pd.read_csv(patch_audit_path))
        except Exception:
            write_pair(output_root, "patch_audit", pd.DataFrame())
    else:
        write_pair(output_root, "patch_audit", pd.DataFrame([{
            "patch_branch": "mfrrecovered035_clfpoollocked",
            "patched_subject": PATCHED_SUBJECT,
            "supervised_classifier_action": "explicitly_excluded",
            "expected_classifier_n": EXPECTED_CLASSIFIER_N,
            "expected_classifier_cn": EXPECTED_CLASSIFIER_CN,
            "expected_classifier_ad": EXPECTED_CLASSIFIER_AD,
        }]))

    primary_cols = ["candidate_id", "condition_id", "channels", "readout_feature_set", "auc", "pr_auc", "balanced_accuracy", "sensitivity", "specificity", "f1"]
    readme = [
        "# Conditional beta-VAE Manufacturer FAST-long 3x3 — recovered-035 VAE pool, classifier pool locked — Aggregation",
        "",
        f"Generated UTC: {now_utc()}",
        "",
        "## Metadata patch",
        "",
        "035_S_6927 restored to VAE pool with Manufacturer=SIEMENS (direct idaSearch evidence).",
        "128_S_2002 remains excluded (unresolvable; no ADNI record).",
        "Patched metadata: `metadata/training_ready_metadata_v5_1b_mfrrecovered035_clfpoollocked.csv` (647 rows).",
        "035_S_6927 is explicitly excluded from supervised classifier train/dev/test.",
        "Expected classifier pool: n=396, CN=300, AD=96.",
        "",
        "## Baseline validity",
        "",
        "Primary comparator: clfpoollocked matched baseline `ch1_0_2_baseline_unconditioned`.",
        "Focused target: `[1,0,2]`, selected from the training-maturity audit over `[1]`.",
        "cleanmfr is used only to audit classifier pool identity.",
        "",
        "Primary readout: Stage B classifier-only `logreg_l2` with `inner_oof_target_sens_ge_0p70_max_spec`.",
        "",
        "## Primary Results",
        "",
        md_table(primary[[c for c in primary_cols if c in primary.columns]] if not primary.empty else primary),
        "",
        "## VAE Pool Filter QC",
        "",
        md_table(qc_summary_all),
        "",
        "## Decision",
        "",
        "See `final_recommendation.md`.",
    ]
    (output_root / "README.md").write_text("\n".join(readme), encoding="utf-8")
    (output_root / "final_recommendation.md").write_text(
        recommendation(primary, latent_info, leakage, predictability, subgroups, pooled_metric_audit),
        encoding="utf-8",
    )
    (output_root / "command_log.json").write_text(json.dumps(command_log, indent=2), encoding="utf-8")
    print(json.dumps(command_log, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
