#!/usr/bin/env python3
"""
Surgical in-place patch of notebook 04_a_fatigue_connectome_baselines.ipynb
to satisfy the adversarial audit requirements.

Changes:
  Cell 6  (§3 heading)  — add NOMINAL/EXPLORATORY banner
  Cell 8  (§4 heading)  — add NOMINAL label
  Cell 14 (§7 heading)  — strong SUPERSEDED warning
  Cell 15 (§7 code)     — add superseded banner and relabel caption
  INSERT after cell 15  — hardening evidence summary code cell
  Cell 16 (§8 heading)  — unchanged (already correct)
  INSERT after cell 16  — final INDETERMINATE verdict stamp code cell
"""
import json
import uuid
from pathlib import Path

NB_PATH = Path(__file__).resolve().parents[1] / "notebooks" / "04_a_fatigue_connectome_baselines.ipynb"

nb = json.load(NB_PATH.open())
cells = nb["cells"]


def _id():
    return uuid.uuid4().hex[:8]


def _code_cell(source: str, cell_id: str = None) -> dict:
    return {
        "cell_type": "code",
        "id": cell_id or _id(),
        "metadata": {"language": "python"},
        "source": source,
        "outputs": [],
        "execution_count": None,
    }


def _md_cell(source: str, cell_id: str = None) -> dict:
    return {
        "cell_type": "markdown",
        "id": cell_id or _id(),
        "metadata": {"language": "markdown"},
        "source": source,
        "outputs": [],
    }


# ── Patch by cell index (0-based) ─────────────────────────────────────

# Cell 6 (index 6): §3 heading — add NOMINAL/EXPLORATORY banner
cells[6]["source"] = (
    "## §3 — Baseline AUC Comparison (NOMINAL / EXPLORATORY LAYER)\n"
    "\n"
    "> ⚠️ **This section is nominal and exploratory.** Results here use best-single-channel\n"
    "> nominal permutation p-values without multiplicity correction.\n"
    "> They are NOT the notebook's authoritative conclusion — see §8.\n"
    "\n"
    "Each bar shows cross-validated AUC. The **dashed line at 0.5** is chance level.\n"
    "★ marks nominal perm p < 0.05 for that single channel (uncorrected for 7 channels tested).\n"
)

# Cell 8 (index 8): §4 heading — add NOMINAL label
cells[8]["source"] = (
    "## §4 — Permutation Null Assessment (NOMINAL / EXPLORATORY LAYER)\n"
    "\n"
    "> ⚠️ **Nominal single-channel p-values only.** These are NOT corrected for\n"
    "> 7-channel selection. The multiplicity-corrected assessment is in §8.\n"
    "\n"
    "A baseline is meaningful only if its AUC significantly exceeds the\n"
    "permutation null (p < 0.05). Bars below the dashed red line survive at this\n"
    "nominal threshold — necessary but NOT sufficient evidence.\n"
)

# Cell 14 (index 14): §7 heading — strong SUPERSEDED warning
cells[14]["source"] = (
    "## §7 — Nominal Decision Table (SUPERSEDED BY §8)\n"
    "\n"
    "> ### ⛔ THIS SECTION IS NOT THE AUTHORITATIVE VERDICT\n"
    ">\n"
    "> This table reports **nominal single-channel results without multiplicity correction**.\n"
    "> It is displayed for transparency (full provenance) and is **explicitly superseded**\n"
    "> by the hardened final assessment in **§8**.\n"
    ">\n"
    "> **Do not leave this notebook having read only §7.**\n"
    "> The authoritative verdict is in §8 — **INDETERMINATE**.\n"
    "\n"
    "The `verdict` column leads with INDETERMINATE for any row where hardening\n"
    "criteria (multiplicity, incremental value, female-only) are unsatisfied.\n"
    "See §8 for the complete evidence trail.\n"
)

# Cell 15 (index 15): §7 code — add superseded banner + re-label caption
cells[15]["source"] = (
    "from IPython.display import display, Markdown, HTML\n"
    "\n"
    "# ── Supersede banner ──────────────────────────────────────────────────\n"
    "display(HTML(\n"
    "    \"<div style='background:#fff3cd;border:2px solid #ffc107;padding:12px;\"\n"
    "    \"border-radius:6px;margin-bottom:12px'>\"\n"
    "    \"<b>⚠️  NOMINAL LAYER — SUPERSEDED BY §8</b><br>\"\n"
    "    \"The table below uses nominal single-channel p-values (no multiplicity correction). \"\n"
    "    \"It exists for provenance only. The authoritative hardened verdict is \"\n"
    "    \"<b>INDETERMINATE</b> — see §8.\"\n"
    "    \"</div>\"\n"
    "))\n"
    "\n"
    "# Display decision table\n"
    "display(dec.style.set_caption(\n"
    "    \"Stop / Go Decision Table — NOMINAL ONLY (authoritative verdict: §8 INDETERMINATE)\"\n"
    ").format(precision=4, na_rep='—'))\n"
    "\n"
    "# Cross-target interpretation (from script output)\n"
    "print('\\n' + '=' * 60)\n"
    "print('CROSS-TARGET INTERPRETATION (nominal layer)')\n"
    "print('=' * 60)\n"
    "print(cross)\n"
    "print('\\n⚑  THIS OUTPUT IS NOMINAL — §8 IS THE AUTHORITATIVE VERDICT')\n"
)

# ── INSERT new cell after index 15 (hardening evidence code cell) ─────
hardening_code = (
    "import json as _json\n"
    "\n"
    "# ── Load hardening evidence (generated by run_fatigue_hardening.py) ───\n"
    "_mp_d_path  = TABLES / 'hardening_D_max_perm.json'\n"
    "_iv_d_path  = TABLES / 'hardening_D_incremental_value.json'\n"
    "_iv_d3_path = TABLES / 'hardening_D_incremental_value_ch3.json'\n"
    "_bh_path    = TABLES / 'hardening_holm_bh_corrections.csv'\n"
    "_mp_e_path  = TABLES / 'hardening_E_max_perm.json'\n"
    "\n"
    "hard_evidence_available = (\n"
    "    _mp_d_path.exists() and _iv_d_path.exists() and _bh_path.exists()\n"
    ")\n"
    "\n"
    "if hard_evidence_available:\n"
    "    mp_d  = _json.loads(_mp_d_path.read_text())\n"
    "    iv_d  = _json.loads(_iv_d_path.read_text())\n"
    "    bh_df = pd.read_csv(_bh_path)\n"
    "    mp_e  = _json.loads(_mp_e_path.read_text()) if _mp_e_path.exists() else {}\n"
    "    iv_d3 = _json.loads(_iv_d3_path.read_text()) if _iv_d3_path.exists() else {}\n"
    "\n"
    "    _CHNAMES = [\n"
    "        'Pearson_OMST', 'Pearson_FisherZ', 'MI_KNN',\n"
    "        'dFC_AbsDiffMean', 'dFC_StdDev', 'DistanceCorr', 'Granger'\n"
    "    ]\n"
    "    _best_resid_ch = int(mp_d.get('best_resid_ch', 0))\n"
    "    _corr_p_resid  = float(mp_d.get('corrected_p_resid', 1.0))\n"
    "    _delta_p       = float(iv_d.get('delta_p', 1.0))\n"
    "    _delta_ci      = iv_d.get('delta_ci', [None, None])\n"
    "    _max_sex_auc   = float(df_diag[df_diag['label'].str.startswith('sex_diag')]['auc_cv'].max())\n"
    "    _mp_e_corr_p   = float(mp_e.get('corrected_p_resid', 1.0))\n"
    "\n"
    "    _bh_d_resid = bh_df[(bh_df['target'] == 'D') & (bh_df['condition'] == 'resid')]['bh_fdr_q']\n"
    "    _best_bh_q  = float(_bh_d_resid.min()) if len(_bh_d_resid) else float('nan')\n"
    "\n"
    "    print('=' * 70)\n"
    "    print('HARDENED EVIDENCE SUMMARY (§8 source data)')\n"
    "    print('=' * 70)\n"
    "    print()\n"
    "    _best_ch_name = _CHNAMES[_best_resid_ch]\n"
    "    print(f'(a) Max-perm correction — Target D (7 channels tested):')\n"
    "    print(f'    Best resid ch = {_best_resid_ch} ({_best_ch_name})')\n"
    "    print(f'    AUC = {mp_d[\"best_resid_auc\"]:.4f}')\n"
    "    _crit_a = 'FAIL' if _corr_p_resid >= 0.05 else 'PASS'\n"
    "    print(f'    Corrected p (max-perm resid) = {_corr_p_resid:.4f}  -> {_crit_a}')\n"
    "    print(f'    Best BH FDR q (any resid ch) = {_best_bh_q:.4f}  (marginal)')\n"
    "    print()\n"
    "    print(f'(b) Incremental value over Age+Sex:')\n"
    "    print(f'    Metadata-only AUC  = {iv_d[\"auc_metadata\"]:.4f}')\n"
    "    print(f'    Connectome-only AUC = {iv_d[\"auc_connectome_resid\"]:.4f}')\n"
    "    print(f'    Connectome 95% CI = [{_delta_ci[0]:.3f}, {_delta_ci[1]:.3f}]')\n"
    "    print(f'    Combined AUC       = {iv_d[\"auc_combined\"]:.4f}')\n"
    "    _crit_b = 'FAIL (NS)' if _delta_p >= 0.05 else 'PASS'\n"
    "    print(f'    Delta (combined - meta) = {iv_d[\"delta_comb_vs_meta\"]:.4f}  bootstrap p = {_delta_p:.3f}  -> {_crit_b}')\n"
    "    if iv_d3:\n"
    "        print(f'    Alt dFC_AbsDiffMean: delta = {iv_d3[\"delta_comb_vs_meta\"]:.4f}  p = {iv_d3[\"delta_p\"]:.3f}  -> also NS')\n"
    "    print()\n"
    "    print('(c) Female-only (perm p < 0.10 criterion):')\n"
    "    _fem_rows = df_base[df_base['label'].str.startswith('female_') & (df_base['target'] == 'D')]\n"
    "    for _, _fr in _fem_rows.iterrows():\n"
    "        _pp = _fr['perm_p']\n"
    "        _fp_status = 'FAIL' if (pd.isna(_pp) or float(_pp) >= 0.10) else 'PASS'\n"
    "        print(f'    ch={_fr.get(\"channel_name\",\"?\")}  AUC={_fr[\"auc_cv\"]:.3f}  perm_p={_pp:.4f}  -> {_fp_status}')\n"
    "    print()\n"
    "    print(f'(d) Sex-prediction AUC (threshold < 0.70):')\n"
    "    _crit_d = 'PASS' if _max_sex_auc < 0.70 else 'FAIL'\n"
    "    print(f'    Max across channels = {_max_sex_auc:.3f}  -> {_crit_d}')\n"
    "    print()\n"
    "    print('(e) Target E shortcut audit:')\n"
    "    print(f'    E max-perm corrected_p_resid = {_mp_e_corr_p:.4f}')\n"
    "    print(f'    E passes (p=0.005) while D fails (p=0.37) -> shortcut learning confirmed')\n"
    "    print()\n"
    "    print('-' * 70)\n"
    "    print('CRITERIA SCORE: 1/4 (+1 marginal BH q)  ->  VERDICT: INDETERMINATE')\n"
    "    print('-' * 70)\n"
    "else:\n"
    "    print('WARNING: Hardening artifacts not found.')\n"
    "    print('Run: python3 scripts/run_fatigue_hardening.py')\n"
    "    print('Then re-run this notebook.')\n"
)

# Insert hardening code cell AFTER cell 15 (at index 16)
cells.insert(16, _code_cell(hardening_code))

# Cell 17 (now shifted to index 17): §8 heading — unchanged content, but
# we'll insert a final verdict cell AFTER it.
# The §8 heading is now at index 17.

verdict_code = (
    "from IPython.display import display, HTML\n"
    "\n"
    "# ── AUTHORITATIVE FINAL VERDICT STAMP ────────────────────────────────\n"
    "display(HTML(\n"
    "    '<div style=\"background:#fff3cd;border:3px solid #e85d04;padding:20px;'\n"
    "    'border-radius:8px;margin:20px 0;text-align:center\">'\n"
    "    '<h2 style=\"color:#9d0208;margin:0 0 10px 0\">FINAL VERDICT: INDETERMINATE</h2>'\n"
    "    '<p style=\"font-size:15px;margin:0 0 8px 0\">'\n"
    "    'Suggestive nominal signal (Target D AUC ≈ 0.73, 2 channels) does <b>not survive</b> '\n"
    "    \"the notebook's own criteria for CAUTIOUS GO:\"\n"
    "    '</p>'\n"
    "    '<ul style=\"text-align:left;font-size:14px;margin:8px 0\">'\n"
    "    '<li>❌ Max-permutation correction p = 0.37 (criterion: p &lt; 0.05)</li>'\n"
    "    '<li>❌ Incremental Δ over Age+Sex p = 0.22 (criterion: p &lt; 0.05)</li>'\n"
    "    '<li>❌ Female-only: no channel reaches p &lt; 0.17 (criterion: p &lt; 0.10)</li>'\n"
    "    '<li>✅ Sex-prediction AUC &lt; 0.70 (criterion: met)</li>'\n"
    "    '</ul>'\n"
    "    '<p style=\"font-size:14px;margin:8px 0\">'\n"
    "    '<b>Target E: shortcut signal confirmed</b> (E max-perm p_resid = 0.005 vs D p_resid = 0.37 — '\n"
    "    'classifier exploits COVID-vs-CONTROL, not fatigue).'\n"
    "    '</p>'\n"
    "    '<hr style=\"margin:12px 0\">'\n"
    "    '<p style=\"font-size:13px;color:#495057;margin:0\">'\n"
    "    'This does NOT mean the signal is absent — it means the current sample (n = 53) '\n"
    "    'and analytic framework are insufficient to confirm it. '\n"
    "    '<b>Do NOT proceed to fatigue-specific representation learning on this evidence alone.</b>'\n"
    "    '</p>'\n"
    "    '</div>'\n"
    "))\n"
)

# Insert final verdict cell AFTER §8 heading (now at index 17) → insert at 18
cells.insert(18, _code_cell(verdict_code))

nb["cells"] = cells
NB_PATH.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
print(f"Patched {NB_PATH}")
print(f"Total cells: {len(cells)}")
for i, c in enumerate(cells):
    preview = "".join(c.get("source", []))[:70].replace("\n", " ")
    print(f"  {i:2d}: [{c['cell_type']}] {preview!r}")
